config:
  units:
    - "101"
    - "102"
    - "110"
    - "201"
    - "202"
    - "204"
    - "205"
    - "303"
    - "304"
    - "305"
    - "306"
    - "307"
    - "308"
    - "401"
    - "402"
    - "403"
    - "404"
    - "405"
    - "406"
    - "407"
    - "411"
    - "501"
    - "502"
    - "503"
    - "504"
    - "601"
    - "602"
    - "603"
    - "701"
  current_year: "2024"
  current_term: 1
  end_dates:
    term_1: "2024-5-26"
    summer: "2024-7-21"
    term_2: "2024-12-31"
